version: "3"
services:
  docker-usage:
    image: nginx
    volumes:
      - ./docker-usage/docker-usage.sh:/docker-usage.sh
    environment:
      - script_path=${PWD}
      - user=${USER}
    command: sh -c "./docker-usage.sh"

  datadog-agent:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - 8126:8126/tcp
    environment:
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOG_LEVEL=TRACE
      - DD_LOGS_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_AC_EXCLUDE=name:datadog-agent
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_ENV=dev

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
      - "8081:8081"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PW}
      - MONGO_INITDB_DATABASE=${MONGODB_DBNAME}
  web:
    build: .
    volumes:
      - ./data:/home/data
    ports:
      - "8080:8080"
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_DEBUG=true
      - DD_DYNAMIC_INSTRUMENTATION_ENABLED=true
      - MONGO_ACCESS_DB_USER=${MONGODB_USER}
      - MONGO_ACCESS_DB_PW=${MONGODB_PW}
      - MONGO_ACCESS_DB_DBNAME=${MONGODB_DBNAME}
      - DD_RUNTIME_METRICS_ENABLED=true
    depends_on:
      - datadog-agent
      - mongo

  web_copy:
    build: .
    volumes:
      - ./data:/home/data
    ports:
      - "8180:8080"
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_DEBUG=true
      - DD_DYNAMIC_INSTRUMENTATION_ENABLED=true
      - MONGO_ACCESS_DB_USER=${MONGODB_USER}
      - MONGO_ACCESS_DB_PW=${MONGODB_PW}
      - MONGO_ACCESS_DB_DBNAME=${MONGODB_DBNAME}
      - DD_RUNTIME_METRICS_ENABLED=true
    depends_on:
      - datadog-agent
      - mongo
      - web